Моя работа с роутерами, запросами и моделями
gpncr-repos/labor_exchange pull request #16
Opened 2024-06-30 22:59 UTC by alexilushkin

В ходе работы мне удалось добавить новые функции для взаимодействия с таблицами пользователей, вакансий и откликов. Компании могут создавать свои вакансии, обновлять и удалять их. Соискатели работы могут смотреть вакансии и делать на них отклики

2024-07-01 13:00 UTC, Rognak requested changes

2024-07-01 13:00 UTC, Rognak commented on .idea/misc.xml
issue: необходимо убрать лишние файлы

2024-07-01 13:00 UTC, Rognak commented on src/main.py
>  def hello():
pick: метод можно убрать

2024-07-01 13:00 UTC, Rognak commented on src/migrations/versions/4cd6e4f04086_привет_мир.py
pick: имя миграции должно отражать изменения

2024-07-01 13:00 UTC, Rognak commented on src/models/jobs.py
> +    salary_from = sa.Column(sa.Integer, comment="Зарплата от")
issue: зарплата не в интах

зарплата в Decimal (NUMERIC)

2024-07-01 13:00 UTC, Rognak commented on src/queries/jobs.py
> +async def get_all_jobs_by_min_salary(db: AsyncSession, limit: int = 100, salary: int = 0) -> Sequence[Job]:
pick: написать один метод

Необходимо реализовать один метод, который будет фильтровать как по зарплате ДО, так и по зарплате ОТ

2024-07-01 13:00 UTC, Rognak commented on src/queries/jobs.py
> +class OrderBy(str, enum.Enum):
pick: вынести в модуль utils

2024-07-01 13:00 UTC, Rognak commented on src/queries/responses.py
> +    res = await db.delete(query)
issue: это delete, не get

2024-07-01 13:00 UTC, Rognak commented on src/queries/responses.py
> +    query = select(Response).where(Response.user_id == user_id).where(Response.job_id == Job.id)
thought: изменить подход

ты получаешь все отклики для данного пользователя. По каждому отклику есть поле job. Обратившись к нему ты сможешь получить нужную вакансию и отфильтровать её

2024-07-01 13:00 UTC, Rognak commented on src/queries/responses.py
> +async def get_response_by_employer_id(db: AsyncSession, user_id: int, flag: int) -> Sequence[Response]:
pick: метод избыточен

2024-07-01 13:00 UTC, Rognak commented on src/routers/jobs.py
> +async def read_jobs_with_min_salary(
pick: аналогично запросам, можно объединить в один

2024-07-01 13:00 UTC, Rognak commented on src/routers/jobs.py
> +@router.get("/get-queries/1", response_model=List[JobSchema])
issue: имена не соответствуют REST конвенции

https://restfulapi.net/resource-naming/

2024-07-01 13:00 UTC, Rognak commented on src/routers/jobs.py
> +
thought: можно создать поле filter

Например:
filter = {
"is_active": True,
"min_salary": 100,
"max_salary": 200
...
}

И анализируя этот фильтр, ты можешь возвращать подходящие данные

2024-07-01 13:00 UTC, Rognak commented on src/routers/jobs.py
> +        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Вы соискатель. Вам нельзя нанимать сотрудников")
pick: изменить вид сообщения

2024-07-01 13:00 UTC, Rognak commented on src/routers/jobs.py
> +    old_job.description = "Вакансия удалена"
pick: это избыточно

2024-07-01 13:00 UTC, Rognak commented on src/routers/responses.py
> +        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Вы работодатель. Вам нельзя откликаться на вакансии")
pick: аналогично

2024-07-01 13:00 UTC, Rognak commented on src/routers/responses.py
> +    old_response.message = "Отклик удалён"
pick: аналогично - избыточно

2024-07-01 13:00 UTC, Rognak commented on src/routers/user.py
> +    jobs = await jobs_queries.get_all_jobs_by_user_id(db=db, user_id=current_user.id)
praise: хорошо продумано

2024-07-01 13:00 UTC, Rognak commented on src/schemas/jobs.py
> +    salary_from: int
issue: Optional[float]

2024-07-01 14:33 UTC, alexilushkin commented on src/routers/jobs.py
> +        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Вы соискатель. Вам нельзя нанимать сотрудников")
Исправлено

2024-07-01 14:38 UTC, alexilushkin commented on src/routers/responses.py
> +        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Вы работодатель. Вам нельзя откликаться на вакансии")
Исправлено

2024-07-01 14:47 UTC, alexilushkin commented on src/routers/responses.py
> +    old_response.message = "Отклик удалён"
Исправлено

2024-07-01 14:54 UTC, alexilushkin commented on src/main.py
>  def hello():
Исправлено

2024-07-01 16:12 UTC, alexilushkin commented on src/migrations/versions/4cd6e4f04086_привет_мир.py
Исправлено

2024-07-01 16:12 UTC, alexilushkin commented on src/routers/user.py
> +    jobs = await jobs_queries.get_all_jobs_by_user_id(db=db, user_id=current_user.id)
Хорошо

2024-07-01 16:12 UTC, alexilushkin commented on src/schemas/jobs.py
> +    salary_from: int
Исправлено

2024-07-01 16:13 UTC, alexilushkin commented on src/models/jobs.py
> +    salary_from = sa.Column(sa.Integer, comment="Зарплата от")
Исправлено

2024-07-01 16:20 UTC, alexilushkin commented on src/routers/jobs.py
> +    old_job.description = "Вакансия удалена"
Исправлено

2024-07-01 16:28 UTC, alexilushkin commented on src/queries/jobs.py
> +class OrderBy(str, enum.Enum):
Сделано

2024-07-01 16:36 UTC, alexilushkin commented on src/queries/responses.py
> +    res = await db.delete(query)
Исправлено

2024-07-01 17:39 UTC, alexilushkin commented on src/queries/responses.py
> +async def get_response_by_employer_id(db: AsyncSession, user_id: int, flag: int) -> Sequence[Response]:
Исправлено

2024-07-01 17:40 UTC, alexilushkin commented on src/queries/responses.py
> +    query = select(Response).where(Response.user_id == user_id).where(Response.job_id == Job.id)
Исправлено

2024-07-01 18:29 UTC, alexilushkin commented on src/queries/jobs.py
> +async def get_all_jobs_by_min_salary(db: AsyncSession, limit: int = 100, salary: int = 0) -> Sequence[Job]:
Сделано

2024-07-01 18:35 UTC, alexilushkin commented on src/routers/jobs.py
> +async def read_jobs_with_min_salary(
Сделано

2024-07-01 18:37 UTC, alexilushkin commented on src/routers/jobs.py
> +
Я сделал класс FilterBy, аналогичный классу OrderBy в utils. И сделал единый параметр salary в запросе и роутере

2024-07-01 23:16 UTC, alexilushkin commented on src/routers/jobs.py
> +@router.get("/get-queries/1", response_model=List[JobSchema])
Поправил. Я не очень понял, как добавить {id} так, чтобы вместо {id} появлялось число и сохранялись все 4 запроса get

2024-07-02 12:11 UTC, alexilushkin commented on src/routers/jobs.py
> +@router.get("/get-queries/1", response_model=List[JobSchema])
Всё, исправил. Я объединил все get-запросы без авторизации в один, а в запросе с авторизацией написал {id}

2024-08-23 09:30 UTC, closed without merging